language: android
sudo: required
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
    global:
    - ANDROID_API=24
    - EMULATOR_API=21
    - ANDROID_BUILD_TOOLS=24.0.2
    - ADB_INSTALL_TIMEOUT=5
    - MSDKUI_APP_ID_ANDROID=$MSDKUI_APP_ID_ANDROID
    - MSDKUI_APP_TOKEN_ANDROID=$MSDKUI_APP_TOKEN_ANDROID
    - MSDKUI_APP_LICENSE_ANDROID=$MSDKUI_APP_LICENSE_ANDROID
    - SDK_VER=HERE-sdk-3.8.aar

android:
    components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - addon-google_apis-google-19 # google play services
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > 
    "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - chmod +x gradlew
    - ./gradlew dependencies || true

jobs:
  include:
    - stage: fetch HERE SDK
        script:
            aws s3 cp s3://iot-ci-classic-sdk-binary/$SDK_VER $HOME
            echo "Copy SDK"
            cp $HOME/$SDK_VER $HOME/MSDKUIKit/libs/HERE-sdk.aar
            cp $HOME/$SDK_VER $HOME/MSDKUIDemo/libs/HERE-sdk.aar
    - stage: Library Tests
        script:
            echo "Library Run analysis tools,run Tests and assembleRelease"
            ./gradlew clean \
            :MSDKUILib:check -x test \
            :MSDKUILib:testDebugUnitTest \
            :MSDKUILib:assembleRelease -x test
            cp $HOME/MSDKUIKit/MSDKUILib/build/outputs/aar/MSDKUILib-release.aar \
            $HOME/MSDKUIDemo/libs/MSDKUILib.aar
    - stage: Demo App Tests
        script:
            echo "DemoApp Run analysis tools,run Tests and assembleRelease"
            cp $HOME/MSDKUIKit/MSDKUILib/build/outputs/aar/MSDKUILib-release.aar \
            $HOME/MSDKUIDemo/libs/MSDKUILib.aar
            cd $HOME/MSDKUIDemo
            ./gradlew clean
            :MSDKUIApp:check -x test
            :MSDKUIApp:test
