language: android

android:
  components:
    - android-28
    - build-tools-28.0.3
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - pip install --user awscli

jobs:
  include:
    - stage: Library unit tests
      script:
        - aws s3 cp s3://$SDK_URL/$SDK_VER MSDKUIKit/libs/HERE-sdk.aar
        - cd MSDKUIKit
        - ./gradlew -x test :MSDKUILib:check :MSDKUILib:testDebugUnitTest
        - aws s3 cp MSDKUILib/build/outputs/aar/MSDKUILib-release.aar s3://$SDK_URL/MSDKUI-Lib-$TRAVIS_BUILD_NUMBER.aar
    - stage: Demo app tests
      script:
        - aws s3 cp s3://$SDK_URL/$SDK_VER MSDKUIDemo/libs/HERE-sdk.aar
        - aws s3 cp s3://$SDK_URL/MSDKUI-Lib-$TRAVIS_BUILD_NUMBER.aar MSDKUIDemo/libs/MSDKUILib.aar
        - cd MSDKUIDemo
        - ./gradlew :MSDKUIApp:check
