dist : trusty
language: android

android:
  components:
    - android-28
    - build-tools-28.0.3
  licenses:
    - 'android-sdk-license-.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install --user awscli

jobs:
  include:
    - stage: Library unit tests
      script:
        - aws s3 cp s3://$SDK_URL/$SDK_VER MSDKUIKit/libs/HERE-sdk.aar
        - cd MSDKUIKit
        - ./gradlew -x test :MSDKUILib:check :MSDKUILib:testDebugUnitTest :MSDKUILib:jacocoTestDebugReport :MSDKUILib:assembleAndroidTest
        - aws s3 cp MSDKUILib/build/outputs/aar/MSDKUILib-release.aar s3://$SDK_URL/MSDKUI-Lib-$TRAVIS_BUILD_NUMBER.aar
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: Demo app tests
      script:
        - aws s3 cp s3://$SDK_URL/$SDK_VER MSDKUIDemo/libs/HERE-sdk.aar
        - aws s3 cp s3://$SDK_URL/MSDKUI-Lib-$TRAVIS_BUILD_NUMBER.aar MSDKUIDemo/libs/MSDKUILib.aar
        - cd MSDKUIDemo
        - ./gradlew :MSDKUIApp:check :MSDKUIApp:jacocoTestDebugReport :MSDKUIApp:assembleAndroidTest
      after_success:
        - bash <(curl -s https://codecov.io/bash)
