/*
 * Copyright (C) 2017-2018 HERE Europe B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.here.msdkui.guidance.base;

import com.here.android.mpa.common.GeoPosition;
import com.here.android.mpa.common.PositioningManager;
import com.here.android.mpa.guidance.NavigationManager;
import com.here.android.mpa.routing.Maneuver;
import com.here.android.mpa.routing.Route;

import java.lang.ref.WeakReference;

/**
 * Base class for guidance presenters.
 * <p>This class interacts with {@link NavigationManager} and {@link PositioningManager} to support
 * easier handling of guidance events.</p>
 */
public class BaseGuidancePresenter {

    private final NavigationManager mNavigationManager;

    /**
     * Listener for {@link com.here.android.mpa.guidance.NavigationManager.ManeuverEventListener}.
     */
    private final NavigationManager.ManeuverEventListener mManeuverEventListener =
            new NavigationManager.ManeuverEventListener() {
                @Override
                public void onManeuverEvent() {
                    handleManeuverEvent();
                }
            };
    /**
     * Listener for {@link com.here.android.mpa.guidance.NavigationManager.NewInstructionEventListener}.
     */
    private final NavigationManager.NewInstructionEventListener mNewInstructionEventListener =
            new NavigationManager.NewInstructionEventListener() {
                @Override
                public void onNewInstructionEvent() {
                    handleNewInstructionEvent();
                }
            };
    /**
     * Listener for {@link com.here.android.mpa.guidance.NavigationManager.PositionListener}.
     */
    private final NavigationManager.PositionListener mPositionListener =
            new NavigationManager.PositionListener() {
                @Override
                public void onPositionUpdated(final GeoPosition loc) {
                    // handlePositionUpdate();
                }
            };

    private final NavigationManager.GpsSignalListener mGpsSignalListener =
            new NavigationManager.GpsSignalListener() {
                @Override public void onGpsLost() {
                    handleGpsLost();
                }

                @Override public void onGpsRestored() {
                    handleGpsRestore();
                }
            };

    private Route mRoute;

    /**
     * Constructs a new instance using a {@link NavigationManager} instance and
     * a route to follow during guidance.
     *
     * @param navigationManager
     *         a {@link NavigationManager}.
     * @param route
     *         a route to be used for guidance.
     */
    protected BaseGuidancePresenter(NavigationManager navigationManager, Route route) {
        mNavigationManager = navigationManager;
        mRoute = route;
    }

    /**
     * Resumes presenter to start listening to navigation events.
     */
    public void resume() {
        if (mNavigationManager == null) {
            return;
        }
        mNavigationManager.addManeuverEventListener(new WeakReference<>(mManeuverEventListener));
        mNavigationManager.addNewInstructionEventListener(new WeakReference<>(mNewInstructionEventListener));
        mNavigationManager.addPositionListener(new WeakReference<>(mPositionListener));
        mNavigationManager.addGpsSignalListener(new WeakReference<>(mGpsSignalListener));
        handleManeuverEvent();
    }

    /**
     * Pauses presenter to stop listening to navigation events.
     */
    public void pause() {
        if (mNavigationManager == null) {
            return;
        }
        mNavigationManager.removeManeuverEventListener(mManeuverEventListener);
        mNavigationManager.removeNewInstructionEventListener(mNewInstructionEventListener);
        mNavigationManager.removePositionListener(mPositionListener);
        mNavigationManager.removeGpsSignalListener(mGpsSignalListener);
    }

    /**
     * Called after resuming the presenter. Subclasses may override for custom needs.
     */
    protected void handleManeuverEvent() {
        // let the sub class override it, if interested,
    }

    /**
     * Notifies on new instruction events generated by {@link NavigationManager}.
     * Subclasses may override this method if they are interested in the events forwarded by
     * {@link com.here.android.mpa.guidance.NavigationManager.NewInstructionEventListener}.
     */
    protected void handleNewInstructionEvent() {
        // let the sub class override it, if interested,
    }

    /**
     * Notifies when GPS signal is lost.
     */
    protected void handleGpsLost() {
        // let the sub class override it, if interested,
    }

    /**
     * Notifies when GPS signal is restored.
     */
    protected void handleGpsRestore() {
        // let the sub class override it, if interested,
    }

    /**
     * Gets the next {@link Maneuver Maneuver}.
     *
     * @return next {@link Maneuver Maneuver}.
     */
    public Maneuver getNextManeuver() {
        return mNavigationManager.getNextManeuver();
    }

    /**
     * Gets the distance to the next {@link Maneuver Maneuver}.
     *
     * @return distance to next {@link Maneuver Maneuver}.
     */
    public long getNextManeuverDistance() {
        return mNavigationManager.getNextManeuverDistance();
    }

    /**
     * Gets the route that was set to be used for guidance.
     *
     * @return a route.
     */
    public Route getRoute() {
        return mRoute;
    }

    /**
     * Sets a new route that should be used for guidance.
     *
     * @param route
     *         a route.
     */
    public void setRoute(Route route) {
        this.mRoute = route;
    }
}